### ISSUE TITLE
Gulp migration

### ISSUE THREAD

**Issue by lexich** [snphq/generator-sp#17]
https://github.com/snphq/generator-sp/tree/gulp

Features
- [x] repair project generation for gulp #18
- [x] revision #19
- [x] preprocess jade templates #20
- [x] javascript proxy #21
- [x] file copy from external folders #22
- [x] separate gulp infrastructure #23
- [x] coffeelinter #24
- [x] notify (about errors) #25
- [x] remove grunt config #26
- [x] remove javascript & swig configuration #27
- [x] add plumber to control errors #29 
- [x] add spritesmit to gulp #35

**Comment by lexich** [comment]
@snphq/members Migration complete

**Comment by sponomarev** [comment]
Great work is done! :+1:
